### ISSUE TITLE
MathType for CKEditor not working on internet explore 11

### ISSUE THREAD

**Issue by jainketan6333** [wiris/mathtype-integration-php#1]
Hello Team,

I am using external integration of mathType and chemType for ckeditor 4.14, ckeditor 4.14 is working fine on internet explore 11,10,9 but when i click on mathType or chemType icon it throws an exception -  `SCRIPT5007: Object.keys: argument is not an Object`

And seems to point to this line in the minified JS:

`{key:"httpBuildQuery",value:function(t){var i="";return Object.keys(t).forEach(function(n){null!=t[n]&&(i+="".concat(e.urlEncode(n),"=").concat(e.urlEncode(t[n]),"&"))}),"&"===i.substring(i.length-1)&&(i=i.substring(0,i.length-1)),i}`

i guess wiris team had fixed this for moodle atto in release [7.15](https://docs.wiris.com/en/mathtype/integrations/release_notes/start#release_715_-_july_2019) but it seems like team did not fixed this for external integration of mathType and chemType for ckeditor 4.14 or might be they didn't updated the external integration plugin **https://www.wiris.net/demo/plugins/ckeditor/plugin.js** 

@manuelwiris @wirismath **It is quit important for me, please help me in this asap**

**Comment by jainketan** [comment]
Hello Team,

any update on this ??

@manuelwiris @wirismath this is very important for me, please help me in this as soon as possible.

**Comment by carlawiris** [comment]
Hello,

Sorry for the late response. The issue should be solved in the last version.
