### ISSUE TITLE
How to integrate to laravel framework

### ISSUE THREAD

**Issue by muni510** [wiris/mathtype-integration-php#4]
Hi Team,

We have added CKEditor in our project and added wiris mathtype plugins.
Our project has been developed in laravel.
But can you please guide to integrate with laravel framework?

**Comment by carla-at-wiris** [comment]
Hello @muni510,

I recommend you to use our [npm packages](https://www.npmjs.com/~wiris) or downoad the [integration from the store](https://store.wiris.com/en/products/downloads/mathtype/integrations).

If you have further questions, please contact us at the <support@wiris.com> email.
